apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    tier: myapp
spec:
  selector:
    matchLabels:
      tier: myapp
  replicas: 3
  template:
    metadata:
      name: frontend
      labels:
        tier: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:nginx:1.22-perl
